package ASSRONE.backend.config;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Reproduces a real, pre-existing documents table (created before the
 * visibility feature existed) and verifies
 * V3__add_documents_visibility_column.sql backfills every historical row to
 * MEMBERS, makes the column NOT NULL, and preserves all data. Runs against
 * real Postgres via Testcontainers. Baselined at version 2 so only V3 is
 * exercised: V1/V2 target unrelated tables this scenario does not need.
 */
@Testcontainers(disabledWithoutDocker = true)
class FlywayDocumentsVisibilityMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    private static final AtomicInteger DB_COUNTER = new AtomicInteger();

    private static final String CREATE_TABLE_SQL = """
            CREATE TABLE documents (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title VARCHAR(255) NOT NULL,
                description VARCHAR(500),
                original_filename VARCHAR(255) NOT NULL,
                stored_filename VARCHAR(255) NOT NULL UNIQUE,
                content_type VARCHAR(255) NOT NULL,
                file_size BIGINT NOT NULL,
                uploaded_by VARCHAR(255) NOT NULL,
                uploaded_at TIMESTAMP
            )
            """;

    private String createFreshDatabase() throws SQLException {
        String dbName = "documents_migration_test_" + DB_COUNTER.incrementAndGet();
        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE DATABASE " + dbName);
        }
        return "jdbc:postgresql://" + postgres.getHost() + ":" + postgres.getMappedPort(5432) + "/" + dbName;
    }

    private void execute(String jdbcUrl, String sql) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }

    private long countRows(String jdbcUrl, String query) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private Flyway flywayFor(String jdbcUrl) {
        return Flyway.configure()
                .dataSource(jdbcUrl, postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("2")
                .load();
    }

    @Test
    void migrationBackfillMembersEtRendLaColonneObligatoireSansPerteDeDonnees() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_TABLE_SQL);
        execute(jdbcUrl, """
                INSERT INTO documents (title, original_filename, stored_filename, content_type, file_size, uploaded_by, uploaded_at)
                VALUES ('Statuts', 'statuts.pdf', 'aaaa-1111', 'application/pdf', 1024, 'admin@assrone.ch', now())
                """);
        execute(jdbcUrl, """
                INSERT INTO documents (title, original_filename, stored_filename, content_type, file_size, uploaded_by, uploaded_at)
                VALUES ('Charte', 'charte.pdf', 'bbbb-2222', 'application/pdf', 2048, 'admin@assrone.ch', now())
                """);

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM documents WHERE visibility = 'MEMBERS'")).isEqualTo(2);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM documents")).isEqualTo(2);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM documents WHERE title = 'Statuts' AND stored_filename = 'aaaa-1111'"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT is_nullable = 'NO' AS not_null FROM information_schema.columns "
                        + "WHERE table_name = 'documents' AND column_name = 'visibility'"))
                .isEqualTo(1);

        assertThatThrownBy(() -> execute(jdbcUrl, """
                INSERT INTO documents (title, original_filename, stored_filename, content_type, file_size, uploaded_by, uploaded_at)
                VALUES ('Sans visibilité', 'x.pdf', 'cccc-3333', 'application/pdf', 10, 'admin@assrone.ch', now())
                """))
                .isInstanceOf(SQLException.class);
    }

    @Test
    void migrationEstIdempotenteSurUneBaseSansDocument() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_TABLE_SQL);

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM documents")).isEqualTo(0);
        assertThat(countRows(jdbcUrl,
                "SELECT is_nullable = 'NO' AS not_null FROM information_schema.columns "
                        + "WHERE table_name = 'documents' AND column_name = 'visibility'"))
                .isEqualTo(1);
    }
}
