package ASSRONE.backend.config;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Verifies V5__create_refresh_tokens_table.sql against real Postgres via
 * Testcontainers: the table, its unique jti index and user_id index are
 * created, a row referencing an existing user can be inserted, and deleting
 * the referenced user cascades to its refresh tokens.
 *
 * Baselined at version 4 so only V5 is exercised, mirroring the sibling
 * migration tests. V5's FK targets "users", a table Flyway itself never
 * creates (it is created by Hibernate ddl-auto before Flyway runs — see
 * FlywayStartupMigrator); a minimal users table is created manually here,
 * both to make the schema non-empty for baselineOnMigrate and to give the
 * FK a real target to reference.
 */
@Testcontainers(disabledWithoutDocker = true)
class FlywayRefreshTokensMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    private static final AtomicInteger DB_COUNTER = new AtomicInteger();

    private static final String CREATE_USERS_TABLE_SQL = """
            CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR(255) NOT NULL UNIQUE
            )
            """;

    private String createFreshDatabase() throws SQLException {
        String dbName = "refresh_tokens_migration_test_" + DB_COUNTER.incrementAndGet();
        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE DATABASE " + dbName);
        }
        return "jdbc:postgresql://" + postgres.getHost() + ":" + postgres.getMappedPort(5432) + "/" + dbName;
    }

    private void execute(String jdbcUrl, String sql) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }

    private long countRows(String jdbcUrl, String query) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private Flyway flywayFor(String jdbcUrl) {
        return Flyway.configure()
                .dataSource(jdbcUrl, postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("4")
                .load();
    }

    @Test
    void migrationCreeLaTableAvecSesIndexEtAcceptelUnRefreshTokenValide() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'uk_refresh_tokens_jti'")).isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'idx_refresh_tokens_user_id'")).isEqualTo(1);

        execute(jdbcUrl, """
                INSERT INTO refresh_tokens (user_id, jti, token_hash, expires_at, created_at)
                VALUES (1, 'jti-1234', 'a'||repeat('0', 63), now() + interval '7 days', now())
                """);

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM refresh_tokens WHERE jti = 'jti-1234'")).isEqualTo(1);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM refresh_tokens WHERE revoked_at IS NULL")).isEqualTo(1);
    }

    @Test
    void colonneJtiEstUniqueEtRefuseUnDoublon() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();

        execute(jdbcUrl, """
                INSERT INTO refresh_tokens (user_id, jti, token_hash, expires_at, created_at)
                VALUES (1, 'jti-doublon', 'a'||repeat('0', 63), now() + interval '7 days', now())
                """);

        assertThatThrownBy(() -> execute(jdbcUrl, """
                INSERT INTO refresh_tokens (user_id, jti, token_hash, expires_at, created_at)
                VALUES (1, 'jti-doublon', 'b'||repeat('0', 63), now() + interval '7 days', now())
                """))
                .isInstanceOf(SQLException.class);
    }

    @Test
    void suppressionDeLUtilisateurEntraineLaSuppressionEnCascadeDeSesRefreshTokens() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();
        execute(jdbcUrl, """
                INSERT INTO refresh_tokens (user_id, jti, token_hash, expires_at, created_at)
                VALUES (1, 'jti-a-supprimer', 'a'||repeat('0', 63), now() + interval '7 days', now())
                """);

        execute(jdbcUrl, "DELETE FROM users WHERE id = 1");

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM refresh_tokens")).isZero();
    }

    @Test
    void reexecuterLaMigrationNeDupliqueRienEtResteIdempotente() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        Flyway flyway = flywayFor(jdbcUrl);

        flyway.migrate();
        int secondRunCount = flyway.migrate().migrationsExecuted;

        assertThat(secondRunCount).isZero();
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM flyway_schema_history WHERE version = '5' AND success = true"))
                .isEqualTo(1);
    }
}
