package ASSRONE.backend.config;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Exercises V1__create_membership_application_pending_index.sql directly against
 * real Postgres databases, bypassing the Spring context entirely, so each of the
 * four database states the migration must handle can be reproduced precisely:
 * empty database, existing table with no Flyway history, existing table without
 * PENDING duplicates, and existing table with PENDING duplicates.
 */
@Testcontainers(disabledWithoutDocker = true)
class FlywayMembershipApplicationMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    private static final AtomicInteger DB_COUNTER = new AtomicInteger();

    private static final String CREATE_TABLE_SQL = """
            CREATE TABLE membership_applications (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name VARCHAR(255) NOT NULL,
                email VARCHAR(255) NOT NULL,
                phone VARCHAR(255),
                membership_type VARCHAR(255) NOT NULL,
                message VARCHAR(1000),
                charter_accepted BOOLEAN NOT NULL,
                status VARCHAR(255),
                submitted_at TIMESTAMP
            )
            """;

    private String createFreshDatabase() throws SQLException {
        String dbName = "migration_test_" + DB_COUNTER.incrementAndGet();
        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE DATABASE " + dbName);
        }
        return "jdbc:postgresql://" + postgres.getHost() + ":" + postgres.getMappedPort(5432) + "/" + dbName;
    }

    private void execute(String jdbcUrl, String sql) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }

    private long countRows(String jdbcUrl, String query) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private Flyway flywayFor(String jdbcUrl) {
        return Flyway.configure()
                .dataSource(jdbcUrl, postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("0")
                .load();
    }

    private static String causeChain(Throwable ex) {
        StringBuilder sb = new StringBuilder();
        for (Throwable t = ex; t != null; t = t.getCause()) {
            sb.append(t.getMessage()).append(" | ");
        }
        return sb.toString();
    }

    @Test
    void migrationEchoueSurUneBaseSansLaTable() throws SQLException {
        String jdbcUrl = createFreshDatabase();

        assertThatThrownBy(() -> flywayFor(jdbcUrl).migrate())
                .isInstanceOf(FlywayException.class)
                .satisfies(ex -> assertThat(causeChain(ex)).containsIgnoringCase("membership_applications"));
    }

    @Test
    void migrationReussitSurUneBaseExistanteSansHistoriqueFlywayEtSansDoublon() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_TABLE_SQL);
        execute(jdbcUrl, """
                INSERT INTO membership_applications (full_name, email, membership_type, charter_accepted, status, submitted_at)
                VALUES ('Jean Dupont', 'jean@example.com', 'INDIVIDUEL', true, 'PENDING', now())
                """);
        execute(jdbcUrl, """
                INSERT INTO membership_applications (full_name, email, membership_type, charter_accepted, status, submitted_at)
                VALUES ('Ancien Rejete', 'rejete@example.com', 'INDIVIDUEL', true, 'REJECTED', now())
                """);
        execute(jdbcUrl, """
                INSERT INTO membership_applications (full_name, email, membership_type, charter_accepted, status, submitted_at)
                VALUES ('Ancien Rejete Bis', 'rejete@example.com', 'INDIVIDUEL', true, 'REJECTED', now())
                """);

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM flyway_schema_history WHERE version = '0' AND type = 'BASELINE'"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM flyway_schema_history WHERE version = '1' AND success = true"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'uk_membership_application_pending_email'"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM membership_applications")).isEqualTo(3);
    }

    @Test
    void migrationEchoueSiDesCandidaturesPendingSontEnDoublonEtNeSupprimeAucuneLigne() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_TABLE_SQL);
        execute(jdbcUrl, """
                INSERT INTO membership_applications (full_name, email, membership_type, charter_accepted, status, submitted_at)
                VALUES ('Doublon Un', 'DOUBLON@example.com', 'INDIVIDUEL', true, 'PENDING', now())
                """);
        execute(jdbcUrl, """
                INSERT INTO membership_applications (full_name, email, membership_type, charter_accepted, status, submitted_at)
                VALUES ('Doublon Deux', '  doublon@example.com  ', 'INDIVIDUEL', true, 'PENDING', now())
                """);

        assertThatThrownBy(() -> flywayFor(jdbcUrl).migrate())
                .isInstanceOf(FlywayException.class)
                .satisfies(ex -> assertThat(causeChain(ex))
                        .containsIgnoringCase("PENDING en doublon")
                        .contains("GROUP BY lower(btrim(email))"));

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM membership_applications")).isEqualTo(2);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'uk_membership_application_pending_email'"))
                .isEqualTo(0);
    }
}
