package ASSRONE.backend.config;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.FlywayException;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Verifies V6__add_users_username_unique_constraint.sql against real
 * Postgres via Testcontainers: the constraint is created, a duplicate
 * username is rejected at the DB level, and a database that already
 * contains duplicate usernames fails the migration loudly instead of
 * silently picking a "winner" among them.
 *
 * Baselined at version 5 so only V6 is exercised, mirroring the sibling
 * migration tests. A minimal users table is created manually here since
 * Hibernate (not Flyway) normally owns it — see FlywayRefreshTokensMigrationTest
 * for the same reasoning.
 */
@Testcontainers(disabledWithoutDocker = true)
class FlywayUsersUsernameUniqueMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    private static final AtomicInteger DB_COUNTER = new AtomicInteger();

    private static final String CREATE_USERS_TABLE_SQL = """
            CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR(255) NOT NULL UNIQUE,
                username VARCHAR(255) NOT NULL,
                password VARCHAR(255) NOT NULL
            )
            """;

    private String createFreshDatabase() throws SQLException {
        String dbName = "users_username_migration_test_" + DB_COUNTER.incrementAndGet();
        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE DATABASE " + dbName);
        }
        return "jdbc:postgresql://" + postgres.getHost() + ":" + postgres.getMappedPort(5432) + "/" + dbName;
    }

    private void execute(String jdbcUrl, String sql) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }

    private long countRows(String jdbcUrl, String query) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private static String causeChain(Throwable ex) {
        StringBuilder sb = new StringBuilder();
        for (Throwable t = ex; t != null; t = t.getCause()) {
            sb.append(t.getMessage()).append(" | ");
        }
        return sb.toString();
    }

    private Flyway flywayFor(String jdbcUrl) {
        return Flyway.configure()
                .dataSource(jdbcUrl, postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("5")
                .target("6")
                .load();
    }

    @Test
    void migrationCreeLaContrainteEtRefuseUnUsernameEnDoublon() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email, username, password) VALUES ('pacogalasso@gmail.com', 'pacogalasso', 'x')");

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_constraint WHERE conname = 'uk_users_username'")).isEqualTo(1);

        assertThatThrownBy(() -> execute(jdbcUrl,
                "INSERT INTO users (email, username, password) VALUES ('pacogalasso@icloud.com', 'pacogalasso', 'x')"))
                .isInstanceOf(SQLException.class);

        // Un email différent avec un username différent reste autorisé.
        execute(jdbcUrl,
                "INSERT INTO users (email, username, password) VALUES ('pacogalasso@icloud.com', 'pacogalasso2', 'x')");
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM users")).isEqualTo(2);
    }

    @Test
    void migrationEchoueSiDesUsernamesEnDoublonExistentDejaEtNeSupprimeAucuneLigne() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email, username, password) VALUES ('doublon.un@example.com', 'doublon', 'x')");
        execute(jdbcUrl, "INSERT INTO users (email, username, password) VALUES ('doublon.deux@example.com', 'doublon', 'x')");

        assertThatThrownBy(() -> flywayFor(jdbcUrl).migrate())
                .isInstanceOf(FlywayException.class)
                .satisfies(ex -> assertThat(causeChain(ex))
                        .containsIgnoringCase("nom(s) d'utilisateur en doublon")
                        .contains("GROUP BY username"));

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM users")).isEqualTo(2);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_constraint WHERE conname = 'uk_users_username'")).isEqualTo(0);
    }

    @Test
    void reexecuterLaMigrationNeDupliqueRienEtResteIdempotente() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        Flyway flyway = flywayFor(jdbcUrl);

        flyway.migrate();
        int secondRunCount = flyway.migrate().migrationsExecuted;

        assertThat(secondRunCount).isZero();
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM flyway_schema_history WHERE version = '6' AND success = true"))
                .isEqualTo(1);
    }
}
