package ASSRONE.backend.config;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Verifies V7__create_user_sessions_table.sql against real Postgres via
 * Testcontainers: the user_sessions table, its unique public_id index and
 * user_id index are created, refresh_tokens gains a NOT NULL session_id FK,
 * every pre-existing refresh_tokens row is backfilled with its own session
 * (no orphan left once the column becomes NOT NULL), and deleting the owning
 * user cascades through both tables.
 *
 * Baselined at version 6 so only V7 is exercised, mirroring the sibling
 * migration tests. A minimal users + refresh_tokens schema is created
 * manually to give V7's backfill and FK something real to operate on.
 */
@Testcontainers(disabledWithoutDocker = true)
class FlywayUserSessionsMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    private static final AtomicInteger DB_COUNTER = new AtomicInteger();

    private static final String CREATE_USERS_TABLE_SQL = """
            CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR(255) NOT NULL UNIQUE
            )
            """;

    private static final String CREATE_REFRESH_TOKENS_TABLE_SQL = """
            CREATE TABLE refresh_tokens (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                jti VARCHAR(36) NOT NULL,
                token_hash VARCHAR(64) NOT NULL,
                expires_at TIMESTAMP NOT NULL,
                revoked_at TIMESTAMP,
                created_at TIMESTAMP NOT NULL
            )
            """;

    private String createFreshDatabase() throws SQLException {
        String dbName = "user_sessions_migration_test_" + DB_COUNTER.incrementAndGet();
        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE DATABASE " + dbName);
        }
        return "jdbc:postgresql://" + postgres.getHost() + ":" + postgres.getMappedPort(5432) + "/" + dbName;
    }

    private void execute(String jdbcUrl, String sql) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }

    private long countRows(String jdbcUrl, String query) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private Flyway flywayFor(String jdbcUrl) {
        return Flyway.configure()
                .dataSource(jdbcUrl, postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("6")
                .target("7")
                .load();
    }

    @Test
    void migrationCreeLaTableAvecSesIndexEtAcceptelUnePublicIdUnique() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, CREATE_REFRESH_TOKENS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'uk_user_sessions_public_id'")).isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'idx_user_sessions_user_id'")).isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'idx_refresh_tokens_session_id'")).isEqualTo(1);

        execute(jdbcUrl, """
                INSERT INTO user_sessions (public_id, user_id, created_at, last_used_at, expires_at)
                VALUES ('11111111-1111-1111-1111-111111111111', 1, now(), now(), now() + interval '7 days')
                """);

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM user_sessions")).isEqualTo(1);
    }

    @Test
    void colonnePublicIdEstUniqueEtRefuseUnDoublon() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, CREATE_REFRESH_TOKENS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();

        execute(jdbcUrl, """
                INSERT INTO user_sessions (public_id, user_id, created_at, last_used_at, expires_at)
                VALUES ('doublon', 1, now(), now(), now() + interval '7 days')
                """);

        assertThatThrownBy(() -> execute(jdbcUrl, """
                INSERT INTO user_sessions (public_id, user_id, created_at, last_used_at, expires_at)
                VALUES ('doublon', 1, now(), now(), now() + interval '7 days')
                """))
                .isInstanceOf(SQLException.class);
    }

    @Test
    void chaqueRefreshTokenExistantEstBackfilleAvecSaPropreSession() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, CREATE_REFRESH_TOKENS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        execute(jdbcUrl, """
                INSERT INTO refresh_tokens (user_id, jti, token_hash, expires_at, revoked_at, created_at)
                VALUES (1, 'jti-actif', 'a'||repeat('0', 63), now() + interval '7 days', NULL, now())
                """);
        execute(jdbcUrl, """
                INSERT INTO refresh_tokens (user_id, jti, token_hash, expires_at, revoked_at, created_at)
                VALUES (1, 'jti-revoque', 'b'||repeat('0', 63), now() + interval '7 days', now(), now())
                """);

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM refresh_tokens WHERE session_id IS NULL")).isZero();
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM user_sessions")).isEqualTo(2);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM user_sessions WHERE revocation_reason = 'MIGRATED_LEGACY_REVOKED'"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl, """
                SELECT COUNT(*) FROM refresh_tokens rt
                JOIN user_sessions us ON us.id = rt.session_id
                WHERE rt.jti = 'jti-actif' AND us.revoked_at IS NULL
                """)).isEqualTo(1);
    }

    @Test
    void sessionIdDevientNonNullApresLeBackfill() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, CREATE_REFRESH_TOKENS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();

        assertThatThrownBy(() -> execute(jdbcUrl, """
                INSERT INTO refresh_tokens (user_id, jti, token_hash, expires_at, created_at)
                VALUES (1, 'jti-sans-session', 'c'||repeat('0', 63), now() + interval '7 days', now())
                """))
                .isInstanceOf(SQLException.class);
    }

    @Test
    void suppressionDeLUtilisateurEntraineLaSuppressionEnCascadeDeSesSessions() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, CREATE_REFRESH_TOKENS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();
        execute(jdbcUrl, """
                INSERT INTO user_sessions (public_id, user_id, created_at, last_used_at, expires_at)
                VALUES ('a-supprimer', 1, now(), now(), now() + interval '7 days')
                """);

        execute(jdbcUrl, "DELETE FROM users WHERE id = 1");

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM user_sessions")).isZero();
    }

    @Test
    void suppressionDeLaSessionEntraineLaSuppressionEnCascadeDeSesRefreshTokens() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, CREATE_REFRESH_TOKENS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();
        execute(jdbcUrl, """
                INSERT INTO user_sessions (public_id, user_id, created_at, last_used_at, expires_at)
                VALUES ('session-a-supprimer', 1, now(), now(), now() + interval '7 days')
                """);
        long sessionId = countRows(jdbcUrl, "SELECT id FROM user_sessions WHERE public_id = 'session-a-supprimer'");
        execute(jdbcUrl, "INSERT INTO refresh_tokens (user_id, session_id, jti, token_hash, expires_at, created_at) "
                + "VALUES (1, " + sessionId + ", 'jti-lie', 'd'||repeat('0', 63), now() + interval '7 days', now())");

        execute(jdbcUrl, "DELETE FROM user_sessions WHERE id = " + sessionId);

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM refresh_tokens WHERE jti = 'jti-lie'")).isZero();
    }

    @Test
    void reexecuterLaMigrationNeDupliqueRienEtResteIdempotente() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, CREATE_REFRESH_TOKENS_TABLE_SQL);
        Flyway flyway = flywayFor(jdbcUrl);

        flyway.migrate();
        int secondRunCount = flyway.migrate().migrationsExecuted;

        assertThat(secondRunCount).isZero();
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM flyway_schema_history WHERE version = '7' AND success = true"))
                .isEqualTo(1);
    }
}
