package ASSRONE.backend.config;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Verifies V9/V10/V11 (email verification column + password-reset and
 * email-verification token tables) against real Postgres via Testcontainers:
 * the column backfill for pre-existing accounts, the token tables' shape
 * (hash-only, indexes, FK, NOT NULL, cascading delete), and migration
 * idempotency on re-run. Baselined at version 8 (the last pre-existing
 * migration) so only V9-V11 are exercised, mirroring the sibling migration
 * tests.
 */
@Testcontainers(disabledWithoutDocker = true)
class FlywayAccountLifecycleMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    private static final AtomicInteger DB_COUNTER = new AtomicInteger();

    private static final String CREATE_USERS_TABLE_SQL = """
            CREATE TABLE users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email VARCHAR(255) NOT NULL UNIQUE,
                created_at TIMESTAMP NOT NULL DEFAULT now()
            )
            """;

    private String createFreshDatabase() throws SQLException {
        String dbName = "account_lifecycle_migration_test_" + DB_COUNTER.incrementAndGet();
        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE DATABASE " + dbName);
        }
        return "jdbc:postgresql://" + postgres.getHost() + ":" + postgres.getMappedPort(5432) + "/" + dbName;
    }

    private void execute(String jdbcUrl, String sql) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }

    private long countRows(String jdbcUrl, String query) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private Flyway flywayFor(String jdbcUrl) {
        return Flyway.configure()
                .dataSource(jdbcUrl, postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("8")
                .target("11")
                .load();
    }

    @Test
    void v9BackfillLaColonneDeVerificationPourLesComptesExistantsAvecLeurDateDeCreation() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email, created_at) VALUES ('preexistant@assrone.ch', '2020-01-01 10:00:00')");

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM users WHERE email = 'preexistant@assrone.ch' AND email_verified_at = created_at"))
                .isEqualTo(1);
    }

    // Exact scenario the reviewer flagged: an admin account that existed
    // before V9 must never be locked out of login by the backfill. Same
    // assertion as the member-account test above, but explicit about the
    // admin role since that's the account class most likely to go unnoticed
    // if a future change ever scoped the backfill by role.
    @Test
    void v9BackfilleAussiUnCompteAdministrateurPreexistantSansExceptionDeRole() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "ALTER TABLE users ADD COLUMN role VARCHAR(50) NOT NULL DEFAULT 'USER'");
        execute(jdbcUrl, "INSERT INTO users (email, created_at, role) "
                + "VALUES ('admin-preexistant@assrone.ch', '2019-06-01 08:00:00', 'ADMIN')");
        execute(jdbcUrl, "INSERT INTO users (email, created_at, role) "
                + "VALUES ('membre-preexistant@assrone.ch', '2021-03-15 09:30:00', 'USER')");

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM users WHERE role = 'ADMIN' AND email_verified_at = created_at"))
                .as("pre-existing admin account backfilled identically to a regular member account")
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM users WHERE role = 'USER' AND email_verified_at = created_at"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM users WHERE email_verified_at IS NULL"))
                .as("zero pre-existing accounts of any role left unverified after V9")
                .isZero();
    }

    // A database that already has the column populated (e.g. re-run of a
    // deploy, or a DB that was migrated once already) must never regress an
    // already-verified account back to NULL, and must never overwrite an
    // account that a prior V9 run (or the application itself) already left
    // deliberately NULL.
    @Test
    void reexecuterV9SurUneBaseDejaMigreeNeModifieAucuneValeurExistante() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email, created_at) VALUES ('deja-verifie@assrone.ch', '2020-01-01 10:00:00')");
        execute(jdbcUrl, "INSERT INTO users (email, created_at) VALUES ('jamais-verifie@assrone.ch', '2020-01-01 10:00:00')");
        flywayFor(jdbcUrl).migrate();
        execute(jdbcUrl, "UPDATE users SET email_verified_at = NULL WHERE email = 'jamais-verifie@assrone.ch'");

        // Re-applying V9's own UPDATE statement directly (idempotent by its
        // own WHERE email_verified_at IS NULL guard) simulates what would
        // happen if the migration ever ran twice against the same database.
        execute(jdbcUrl, "UPDATE users SET email_verified_at = created_at WHERE email_verified_at IS NULL");

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM users WHERE email = 'deja-verifie@assrone.ch' AND email_verified_at = '2020-01-01 10:00:00'"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM users WHERE email = 'jamais-verifie@assrone.ch' AND email_verified_at IS NOT NULL"))
                .as("a NULL row re-exposed to the same guarded UPDATE gets backfilled again, exactly like a real first run")
                .isEqualTo(1);
    }

    @Test
    void v9NeVerifiePasSilencieusementUnCompteQuiEtaitDejaMarqueNonVerifie() throws SQLException {
        // Un compte inséré APRÈS la migration (donc jamais backfillé) doit rester
        // NULL par défaut — seule la migration elle-même touche les lignes
        // pré-existantes, jamais les futures inscriptions.
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        flywayFor(jdbcUrl).migrate();

        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('nouveau@assrone.ch')");

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM users WHERE email = 'nouveau@assrone.ch' AND email_verified_at IS NULL"))
                .isEqualTo(1);
    }

    @Test
    void v10CreeLaTableDesTokensDeReinitialisationAvecSesContraintes() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'uk_password_reset_tokens_token_hash'")).isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'idx_password_reset_tokens_user_id'")).isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'idx_password_reset_tokens_expires_at'")).isEqualTo(1);

        execute(jdbcUrl, """
                INSERT INTO password_reset_tokens (user_id, token_hash, created_at, expires_at)
                VALUES (1, 'a'||repeat('0', 63), now(), now() + interval '1 hour')
                """);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM password_reset_tokens")).isEqualTo(1);
    }

    @Test
    void v10RefuseUnDoublonDeTokenHash() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();
        execute(jdbcUrl, """
                INSERT INTO password_reset_tokens (user_id, token_hash, created_at, expires_at)
                VALUES (1, 'b'||repeat('0', 63), now(), now() + interval '1 hour')
                """);

        assertThatThrownBy(() -> execute(jdbcUrl, """
                INSERT INTO password_reset_tokens (user_id, token_hash, created_at, expires_at)
                VALUES (1, 'b'||repeat('0', 63), now(), now() + interval '1 hour')
                """))
                .isInstanceOf(SQLException.class);
    }

    @Test
    void v10RefuseUnTokenSansUtilisateur() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        flywayFor(jdbcUrl).migrate();

        assertThatThrownBy(() -> execute(jdbcUrl, """
                INSERT INTO password_reset_tokens (user_id, token_hash, created_at, expires_at)
                VALUES (999, 'c'||repeat('0', 63), now(), now() + interval '1 hour')
                """))
                .isInstanceOf(SQLException.class);
    }

    @Test
    void v10SuppressionDeLUtilisateurEntraineLaSuppressionEnCascadeDeSesTokensDeReinitialisation() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();
        execute(jdbcUrl, """
                INSERT INTO password_reset_tokens (user_id, token_hash, created_at, expires_at)
                VALUES (1, 'd'||repeat('0', 63), now(), now() + interval '1 hour')
                """);

        execute(jdbcUrl, "DELETE FROM users WHERE id = 1");

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM password_reset_tokens")).isZero();
    }

    @Test
    void v11CreeLaTableDesTokensDeVerificationAvecLesMemesContraintes() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'uk_email_verification_tokens_token_hash'")).isEqualTo(1);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_indexes WHERE indexname = 'idx_email_verification_tokens_user_id'")).isEqualTo(1);

        execute(jdbcUrl, """
                INSERT INTO email_verification_tokens (user_id, token_hash, created_at, expires_at)
                VALUES (1, 'e'||repeat('0', 63), now(), now() + interval '24 hours')
                """);

        assertThatThrownBy(() -> execute(jdbcUrl, """
                INSERT INTO email_verification_tokens (user_id, token_hash, created_at, expires_at)
                VALUES (1, 'e'||repeat('0', 63), now(), now() + interval '24 hours')
                """))
                .isInstanceOf(SQLException.class);
    }

    @Test
    void v11SuppressionDeLUtilisateurEntraineLaSuppressionEnCascadeDeSesTokensDeVerification() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO users (email) VALUES ('membre@assrone.ch')");
        flywayFor(jdbcUrl).migrate();
        execute(jdbcUrl, """
                INSERT INTO email_verification_tokens (user_id, token_hash, created_at, expires_at)
                VALUES (1, 'f'||repeat('0', 63), now(), now() + interval '24 hours')
                """);

        execute(jdbcUrl, "DELETE FROM users WHERE id = 1");

        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM email_verification_tokens")).isZero();
    }

    @Test
    void reexecuterLaMigrationNeDupliqueRienEtResteIdempotente() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_USERS_TABLE_SQL);
        Flyway flyway = flywayFor(jdbcUrl);

        flyway.migrate();
        int secondRunCount = flyway.migrate().migrationsExecuted;

        assertThat(secondRunCount).isZero();
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM flyway_schema_history WHERE version = '11' AND success = true"))
                .isEqualTo(1);
    }
}
