package ASSRONE.backend.config;

import org.flywaydb.core.Flyway;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.concurrent.atomic.AtomicInteger;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Reproduces a real, pre-existing database still carrying the legacy
 * events_type_check constraint that Hibernate's @Enumerated(EnumType.STRING)
 * mapping used to generate for Event.type (see V2's header comment), and
 * verifies V2__drop_events_type_check_constraint.sql removes it without
 * touching any existing row. Runs against real Postgres via Testcontainers,
 * never a mock or H2, since the behavior under test is a Postgres-specific
 * constraint. Baselined at version 1 so only V2 is exercised: V1 targets an
 * unrelated table (membership_applications) that this scenario does not need.
 */
@Testcontainers(disabledWithoutDocker = true)
class FlywayEventsTypeCheckMigrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    private static final AtomicInteger DB_COUNTER = new AtomicInteger();

    private static final String CREATE_TABLE_SQL = """
            CREATE TABLE events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                type VARCHAR(255) NOT NULL,
                CONSTRAINT events_type_check CHECK (type IN ('WEBINAIRE', 'ATELIER', 'CONFERENCE'))
            )
            """;

    private String createFreshDatabase() throws SQLException {
        String dbName = "events_migration_test_" + DB_COUNTER.incrementAndGet();
        try (Connection conn = DriverManager.getConnection(
                postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("CREATE DATABASE " + dbName);
        }
        return "jdbc:postgresql://" + postgres.getHost() + ":" + postgres.getMappedPort(5432) + "/" + dbName;
    }

    private void execute(String jdbcUrl, String sql) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute(sql);
        }
    }

    private long countRows(String jdbcUrl, String query) throws SQLException {
        try (Connection conn = DriverManager.getConnection(jdbcUrl, postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement();
             ResultSet rs = stmt.executeQuery(query)) {
            rs.next();
            return rs.getLong(1);
        }
    }

    private Flyway flywayFor(String jdbcUrl) {
        return Flyway.configure()
                .dataSource(jdbcUrl, postgres.getUsername(), postgres.getPassword())
                .locations("classpath:db/migration")
                .baselineOnMigrate(true)
                .baselineVersion("1")
                // Stops right after V2, the migration under test. Without this, migrate()
                // would keep applying every later migration on the classpath (V3+), each of
                // which targets a table this test's minimal schema never creates.
                .target("2")
                .load();
    }

    @Test
    void migrationSupprimeLaContrainteLegacyEtPreserveLesDonneesExistantes() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, CREATE_TABLE_SQL);
        execute(jdbcUrl, "INSERT INTO events (type) VALUES ('WEBINAIRE')");

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_constraint WHERE conname = 'events_type_check'"))
                .isEqualTo(1);
        assertThatThrownBy(() -> execute(jdbcUrl, "INSERT INTO events (type) VALUES ('Assemblée générale')"))
                .isInstanceOf(SQLException.class);

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_constraint WHERE conname = 'events_type_check'"))
                .isEqualTo(0);
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM events WHERE type = 'WEBINAIRE'"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM events")).isEqualTo(1);

        execute(jdbcUrl, "INSERT INTO events (type) VALUES ('Assemblée générale')");
        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM events WHERE type = 'Assemblée générale'"))
                .isEqualTo(1);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM events")).isEqualTo(2);
    }

    @Test
    void migrationEstIdempotenteSansContrainteExistante() throws SQLException {
        String jdbcUrl = createFreshDatabase();
        execute(jdbcUrl, """
                CREATE TABLE events (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    type VARCHAR(255) NOT NULL
                )
                """);
        execute(jdbcUrl, "INSERT INTO events (type) VALUES ('Assemblée générale')");

        flywayFor(jdbcUrl).migrate();

        assertThat(countRows(jdbcUrl,
                "SELECT COUNT(*) FROM pg_constraint WHERE conname = 'events_type_check'"))
                .isEqualTo(0);
        assertThat(countRows(jdbcUrl, "SELECT COUNT(*) FROM events")).isEqualTo(1);
    }
}
