-- Backs the "mot de passe oublié" flow. Only a SHA-256 hash of the opaque
-- token is ever stored (see TokenHasher/SecureTokenGenerator) — the raw
-- token exists only in memory long enough to email it, so a database read
-- alone can never yield a usable reset link. used_at is null until the
-- token is consumed; a row's presence with used_at IS NULL and expires_at in
-- the future is what makes a presented token usable, mirroring the
-- refresh_tokens table's own revoked_at/expires_at pattern exactly.
--
-- ON DELETE CASCADE: a deleted user's outstanding reset tokens are
-- meaningless the moment the account is gone.
CREATE TABLE IF NOT EXISTS password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used_at TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_password_reset_tokens_token_hash ON password_reset_tokens (token_hash);
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_user_id ON password_reset_tokens (user_id);
-- Supports both the scheduled cleanup query (TokenCleanupService) and
-- PasswordResetService's own expiry check.
CREATE INDEX IF NOT EXISTS idx_password_reset_tokens_expires_at ON password_reset_tokens (expires_at);
