-- Creates the committee_members table backing the new admin-managed "Notre
-- équipe" section on the public "À propos" page. Hibernate (ddl-auto=update)
-- would create the columns themselves, but the index below is not something
-- Hibernate generates automatically, and this migration is also the vehicle
-- for a one-time, controlled seed of the committee members that were
-- previously hardcoded in the Angular "about" component. Flyway runs each
-- version exactly once (tracked in flyway_schema_history), so this INSERT
-- never re-runs on subsequent application restarts.
--
-- No photo is seeded (photo_filename stays NULL) — the original hardcoded
-- list never had real photos, only initials. Display order and active state
-- match the current hardcoded order exactly, so the public page keeps
-- showing the same seven entries in the same order.
CREATE TABLE IF NOT EXISTS committee_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(80) NOT NULL,
    last_name VARCHAR(80) NOT NULL,
    role VARCHAR(100) NOT NULL,
    description VARCHAR(1200),
    photo_filename VARCHAR(255),
    display_order INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_committee_members_active_display_order
    ON committee_members (active, display_order);

INSERT INTO committee_members (first_name, last_name, role, description, display_order, active) VALUES
    ('Béatrice', 'Amoroso Galasso', 'Présidente',
     'Diplômée en éducation spécialisée et en neuropédagogie, titulaire d''un master en enseignement spécialisé et d''un DAS en éducation précoce spécialisée, j''accompagne les équipes enseignantes qui accueillent des élèves avec un trouble du spectre de l''autisme (TSA) en proposant des pistes d''intervention concrètes et des sensibilisations ciblées adaptées aux besoins des élèves et à la réalité du terrain.

En parallèle, je conçois et co-anime des ateliers d''habiletés sociales pour enfants, ainsi que des formations destinées aux adultes. Forte d''une expérience auprès d''enfants présentant des troubles du neurodéveloppement (TSA, TDAH, troubles des apprentissages, déficience intellectuelle) et des difficultés de développement, j''interviens avec une approche centrée sur l''enfant et son environnement inclusif — famille, garderie, école.

Mes compétences clés : guidance interactive et accompagnement familial, outils de communication alternative et améliorée (CAA), soutien gestuel et approches psychocorporelles.',
     1, TRUE),
    ('Helena', 'Da Silva', 'Vice-présidente', NULL, 2, TRUE),
    ('Candice', 'Floch', 'Co-secrétaire', NULL, 3, TRUE),
    ('Amélie', 'Gautier Meynier', 'Co-secrétaire', NULL, 4, TRUE),
    ('Sandra', 'Schaller', 'Trésorière', NULL, 5, TRUE),
    ('Isabelle', 'Santarelli', 'Membre du comité', NULL, 6, TRUE),
    ('Poste', 'à pourvoir', 'Membre du comité', NULL, 7, TRUE);
