-- Backs the refresh-token rotation/revocation strategy: each issued refresh
-- token gets one row here, identified by its JWT "jti" claim. The raw JWT is
-- never stored — only a SHA-256 hash of it, so a database read alone can
-- never yield a usable token. A row's presence with revoked_at IS NULL and
-- expires_at in the future is what makes a presented refresh token usable;
-- rotation revokes the old row (revoked_at set) when a new one is issued,
-- and reuse of an already-revoked jti is the reuse-detection signal that
-- triggers revoking every token for that user.
--
-- ON DELETE CASCADE: a deleted user's refresh tokens are meaningless the
-- moment the account is gone, and the account-deletion path (see
-- AdminUserManagementService) already performs a hard delete of the user
-- row, so cascading here avoids leaving orphaned rows behind.
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    jti VARCHAR(36) NOT NULL,
    token_hash VARCHAR(64) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_refresh_tokens_jti ON refresh_tokens (jti);

-- Supports both "find this user's active tokens" (reuse detection needs to
-- revoke all of them) and the periodic-cleanup query an operator would run
-- by hand (expired rows are otherwise harmless — every lookup already checks
-- expires_at — but this index keeps that query cheap if it's ever needed).
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
