CREATE TABLE IF NOT EXISTS user_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id VARCHAR(36) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL,
    last_used_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    revocation_reason VARCHAR(64),
    created_ip VARCHAR(45),
    last_seen_ip VARCHAR(45),
    user_agent_label VARCHAR(255)
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_sessions_public_id ON user_sessions (public_id);
CREATE INDEX IF NOT EXISTS idx_user_sessions_user_id ON user_sessions (user_id);
-- Partial indexes targeting exactly the two predicates the scheduled cleanup
-- job (SessionCleanupService) filters on, so a purge run never needs a
-- sequential scan even as the table grows.
CREATE INDEX IF NOT EXISTS idx_user_sessions_revoked_at ON user_sessions (revoked_at) WHERE revoked_at IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_user_sessions_expires_at_active ON user_sessions (expires_at) WHERE revoked_at IS NULL;

ALTER TABLE refresh_tokens ADD COLUMN IF NOT EXISTS session_id BIGINT;

-- Backfill: one session per pre-existing refresh_tokens row, so that after
-- session_id is made NOT NULL below no row is left orphaned. A temporary
-- correlation column lets the newly-inserted user_sessions rows be matched
-- back to the refresh_tokens row they were derived from; it is dropped once
-- the link is established. Public IDs here are built from md5(random())
-- rather than gen_random_uuid() to avoid depending on the pgcrypto
-- extension, and are unique enough for this one-time backfill of rows that,
-- given the 7-day refresh token lifetime, are already revoked or expired in
-- every environment this migration will ever run against.
ALTER TABLE user_sessions ADD COLUMN legacy_refresh_token_id BIGINT;

INSERT INTO user_sessions (public_id, user_id, created_at, last_used_at, expires_at, revoked_at,
                            revocation_reason, legacy_refresh_token_id)
SELECT
    substr(md5(random()::text || clock_timestamp()::text || rt.id::text), 1, 8) || '-' ||
    substr(md5(random()::text || clock_timestamp()::text || rt.id::text || '2'), 1, 4) || '-' ||
    substr(md5(random()::text || clock_timestamp()::text || rt.id::text || '3'), 1, 4) || '-' ||
    substr(md5(random()::text || clock_timestamp()::text || rt.id::text || '4'), 1, 4) || '-' ||
    substr(md5(random()::text || clock_timestamp()::text || rt.id::text || '5'), 1, 12),
    rt.user_id,
    rt.created_at,
    rt.created_at,
    rt.expires_at,
    rt.revoked_at,
    CASE WHEN rt.revoked_at IS NOT NULL THEN 'MIGRATED_LEGACY_REVOKED' ELSE NULL END,
    rt.id
FROM refresh_tokens rt;

UPDATE refresh_tokens rt
SET session_id = us.id
FROM user_sessions us
WHERE us.legacy_refresh_token_id = rt.id;

ALTER TABLE user_sessions DROP COLUMN legacy_refresh_token_id;

ALTER TABLE refresh_tokens ALTER COLUMN session_id SET NOT NULL;
ALTER TABLE refresh_tokens ADD CONSTRAINT fk_refresh_tokens_session
    FOREIGN KEY (session_id) REFERENCES user_sessions (id) ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_session_id ON refresh_tokens (session_id);
