package ASSRONE.backend.controller;

import ASSRONE.backend.model.User;
import ASSRONE.backend.repository.UserInfoRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Proves that adding failedLoginAttempts/lockedUntil to the User entity is safe
 * against an existing, already-populated "users" table that predates this lot
 * (no failed_login_attempts/locked_until columns yet). The users table is
 * seeded via raw JDBC before the Spring context starts, so Hibernate's
 * ddl-auto=update — not a Flyway migration, see LOT 7b's schema decision — is
 * what must ALTER TABLE safely. If columnDefinition were missing on the new
 * @Column annotations, Hibernate's generated "ADD COLUMN ... NOT NULL" without
 * a default would fail outright against a non-empty table, and this whole test
 * class would fail at context startup rather than at any individual assertion.
 */
@SpringBootTest
@Testcontainers(disabledWithoutDocker = true)
class UserLockoutColumnsSchemaTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    @DynamicPropertySource
    static void datasourceProperties(DynamicPropertyRegistry registry) throws SQLException {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
        seedPreExistingUsersTableWithoutLockoutColumns();
    }

    private static void seedPreExistingUsersTableWithoutLockoutColumns() throws SQLException {
        try (Connection conn = DriverManager.getConnection(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email VARCHAR(255) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        username VARCHAR(255) NOT NULL,
                        first_name VARCHAR(255),
                        last_name VARCHAR(255),
                        avatar_filename VARCHAR(255),
                        role VARCHAR(255) NOT NULL,
                        is_active BOOLEAN NOT NULL,
                        last_login TIMESTAMP,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL
                    )
                    """);
            stmt.execute("""
                    INSERT INTO users (email, password, username, role, is_active, created_at, updated_at)
                    VALUES ('compte.existant@assrone.ch', 'hash-bcrypt-existant', 'compte.existant', 'USER', true, now(), now())
                    """);
        }
    }

    @Autowired
    private UserInfoRepository userInfoRepository;

    @Test
    void demarrageReussitEtLesLignesExistantesRecoiventLesValeursParDefautSansPerteDeDonnees() {
        User existant = userInfoRepository.findByEmail("compte.existant@assrone.ch").orElseThrow();

        assertThat(existant.getFailedLoginAttempts()).isZero();
        assertThat(existant.getLockedUntil()).isNull();
        assertThat(existant.getPassword()).isEqualTo("hash-bcrypt-existant");
        assertThat(existant.getUsername()).isEqualTo("compte.existant");
        assertThat(existant.getIsActive()).isTrue();
    }
}
