package ASSRONE.backend.controller;

import ASSRONE.backend.model.User;
import ASSRONE.backend.repository.UserInfoRepository;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Proves that V8__add_users_lockout_columns.sql safely adds
 * failed_login_attempts/locked_until to an existing, already-populated
 * "users" table that predates them (a real historical state: these columns
 * were originally added via Hibernate's ddl-auto=update ALTER TABLE, before
 * Flyway was given a tracked migration for them — see V8's own header). The
 * users table is seeded via raw JDBC before the Spring context starts,
 * without either column, so Flyway's real migration chain — not Hibernate,
 * which never alters or creates schema anywhere in this application (see
 * application.properties, ddl-auto=validate unconditionally) — is what must
 * apply V8 safely against a non-empty table. If V8's ALTER TABLE lacked a
 * default, adding a NOT NULL column would fail outright against a non-empty
 * table, and this whole test class would fail at context startup rather than
 * at any individual assertion.
 */
@SpringBootTest
@Testcontainers(disabledWithoutDocker = true)
class UserLockoutColumnsSchemaTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:15");

    @DynamicPropertySource
    static void datasourceProperties(DynamicPropertyRegistry registry) throws SQLException {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
        seedPreExistingUsersTableWithoutLockoutColumns();
    }

    private static void seedPreExistingUsersTableWithoutLockoutColumns() throws SQLException {
        try (Connection conn = DriverManager.getConnection(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
             Statement stmt = conn.createStatement()) {
            stmt.execute("""
                    CREATE TABLE users (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        email VARCHAR(255) NOT NULL UNIQUE,
                        password VARCHAR(255) NOT NULL,
                        username VARCHAR(255) NOT NULL,
                        first_name VARCHAR(255),
                        last_name VARCHAR(255),
                        avatar_filename VARCHAR(255),
                        role VARCHAR(255) NOT NULL,
                        is_active BOOLEAN NOT NULL,
                        last_login TIMESTAMP,
                        created_at TIMESTAMP NOT NULL,
                        updated_at TIMESTAMP NOT NULL
                    )
                    """);
            stmt.execute("""
                    INSERT INTO users (email, password, username, role, is_active, created_at, updated_at)
                    VALUES ('compte.existant@assrone.ch', 'hash-bcrypt-existant', 'compte.existant', 'USER', true, now(), now())
                    """);
        }
    }

    @Autowired
    private UserInfoRepository userInfoRepository;

    @Test
    void demarrageReussitEtLesLignesExistantesRecoiventLesValeursParDefautSansPerteDeDonnees() {
        User existant = userInfoRepository.findByEmail("compte.existant@assrone.ch").orElseThrow();

        assertThat(existant.getFailedLoginAttempts()).isZero();
        assertThat(existant.getLockedUntil()).isNull();
        assertThat(existant.getPassword()).isEqualTo("hash-bcrypt-existant");
        assertThat(existant.getUsername()).isEqualTo("compte.existant");
        assertThat(existant.getIsActive()).isTrue();
    }
}
